# Generated by Django 5.1.6 on 2026-02-17 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_brands_and_condition_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('auto', 'AUTO'), ('semi', 'SEMI'), ('manual_oem', 'MANUAL OEM')], default='semi', max_length=20)),
                ('urgency', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('needs_review', 'Needs Review'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('new', 'NEW'), ('auto_matched', 'AUTO MATCHED'), ('needs_review', 'NEEDS REVIEW'), ('oem_manual', 'OEM MANUAL')], default='new', max_length=20)),
                ('matched_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_items', to='marketplace.part')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.rfq')),
            ],
        ),
    ]
