# Generated by Django 5.1.6 on 2026-02-17 10:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_enforce_brand_layout_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='recommended_supplier_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bankruptcy_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='behavioral_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_rating_recalculated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liquidation_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supplier_status',
            field=models.CharField(choices=[('trusted', 'Надёжный'), ('sandbox', 'Песочница'), ('risky', 'Рисковый'), ('rejected', 'Исключён')], default='sandbox', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierRatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rfq_response', 'RFQ Response'), ('data_mismatch', 'Data Mismatch'), ('delivery_delay', 'Delivery Delay'), ('order_cancellation', 'Order Cancellation'), ('return', 'Return'), ('sandbox_selected', 'Sandbox Selected'), ('risky_selected', 'Risky Selected')], max_length=40)),
                ('impact_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rating_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
