# Generated by Django 5.1.6 on 2026-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_rfqitem_confidence_rfqitem_decision_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierratingevent',
            name='event_type',
            field=models.CharField(choices=[('rfq_response', 'RFQ Response'), ('data_mismatch', 'Data Mismatch'), ('delivery_delay', 'Delivery Delay'), ('order_cancellation', 'Order Cancellation'), ('return', 'Return'), ('sandbox_selected', 'Sandbox Selected'), ('risky_selected', 'Risky Selected'), ('manual_oem_escalation', 'Manual OEM Escalation')], max_length=40),
        ),
    ]
