# Generated by Django 5.1.6 on 2026-02-17 10:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_supplierratingevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'IN_STOCK'), ('backorder', 'BACKORDER')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='availability_status',
            field=models.CharField(choices=[('active', 'active'), ('limited', 'limited'), ('made_to_order', 'made_to_order'), ('discontinued', 'discontinued'), ('blocked', 'blocked')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='backorder_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='country_of_origin',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='cross_numbers',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='part',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('CNY', 'CNY')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='part',
            name='data_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='part',
            name='gross_weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.100'), max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='incoterm',
            field=models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('DDP', 'DDP')], default='FOB', max_length=3),
        ),
        migrations.AddField(
            model_name='part',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='mapping_status',
            field=models.CharField(choices=[('auto', 'auto'), ('confirmed', 'confirmed'), ('needs_review', 'needs_review')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='moq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='part',
            name='prep_to_ship_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='part',
            name='production_lead_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='part',
            name='shipping_lead_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier_part_uid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='part',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
    ]
