# Generated by Django 5.1.6 on 2026-02-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_part_availability_part_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_brands',
            field=models.ManyToManyField(blank=True, related_name='allowed_profiles', to='marketplace.brand'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_regions',
            field=models.CharField(blank=True, help_text='CSV list: europe,china,components,...', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_assortment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_drawings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('director', 'Director'), ('sales', 'Sales'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('viewer', 'Viewer')], default='director', max_length=20),
        ),
    ]
