# Generated by Django 5.1.6 on 2026-02-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_userprofile_allowed_brands_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_breaches_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('breached', 'Breached')], default='on_track', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_confirm_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('status_changed', 'Status Changed'), ('sla_status_changed', 'SLA Status Changed'), ('invoice_opened', 'Invoice Opened')], max_length=40)),
                ('source', models.CharField(choices=[('system', 'System'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('operator', 'Operator')], default='system', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
