# Generated by Django 5.1.6 on 2026-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_order_ship_deadline_order_sla_breaches_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_provider',
            field=models.CharField(default='internal_fallback', max_length=60),
        ),
    ]
