# Generated by Django 5.1.6 on 2026-02-18 04:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_order_logistics_cost_order_logistics_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_reserve', 'Awaiting Reserve'), ('reserve_paid', 'Reserve Paid'), ('paid', 'Paid'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='awaiting_reserve', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='reserve_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='reserve_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reserve_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reserve_paid', 'Reserve Paid'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('status_changed', 'Status Changed'), ('sla_status_changed', 'SLA Status Changed'), ('invoice_opened', 'Invoice Opened'), ('reserve_paid', 'Reserve Paid'), ('final_payment_paid', 'Final Payment Paid'), ('quality_confirmed', 'Quality Confirmed')], max_length=40),
        ),
    ]
