# Generated by Django 5.1.6 on 2026-02-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_orderevent_event_type_orderclaim_orderdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocument',
            name='file_obj',
            field=models.FileField(blank=True, upload_to='order_documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('success', models.BooleanField(default=False)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='marketplace.order')),
                ('order_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='marketplace.orderevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
