# Generated by Django 5.1.6 on 2026-03-23 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_sellerimportrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_reserve', 'Ожидает резерва'), ('reserve_paid', 'Резерв оплачен'), ('paid', 'Оплачен'), ('refund_pending', 'Возврат в обработке'), ('refunded', 'Возвращён')], default='awaiting_reserve', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='sla_status',
            field=models.CharField(choices=[('on_track', 'В норме'), ('at_risk', 'Под угрозой'), ('breached', 'Нарушен')], default='on_track', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('reserve_paid', 'Резерв оплачен'), ('confirmed', 'Подтверждён'), ('in_production', 'В производстве'), ('ready_to_ship', 'Готов к отгрузке'), ('shipped', 'Отгружен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент (%)'), ('fixed', 'Фиксированная сумма ($)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_parts', models.ManyToManyField(blank=True, related_name='discounts', to='marketplace.part')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
