# Generated by Django 5.1.6 on 2026-03-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_order_payment_status_alter_order_sla_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='discount_note',
            field=models.CharField(blank=True, help_text='Комментарий к скидке', max_length=255),
        ),
        migrations.AddField(
            model_name='rfq',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая скидка на весь RFQ (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='discount_fixed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фиксированная скидка ($)', max_digits=12),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скидка на позицию (%)', max_digits=5),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
