# Generated by Django 5.1.6 on 2026-03-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_rfq_discount_note_rfq_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание оплаты'), ('reserve_paid', 'Резерв оплачен'), ('confirmed', 'Формирование заказа'), ('in_production', 'В производстве'), ('ready_to_ship', 'Готов к отгрузке'), ('transit_abroad', 'Транзит (Зарубеж)'), ('customs', 'Таможня'), ('transit_rf', 'Транзит (РФ)'), ('issuing', 'Выдача'), ('shipped', 'Отгружен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('dwg', 'DWG'), ('dxf', 'DXF'), ('step', 'STEP'), ('iges', 'IGES'), ('stl', 'STL'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=10)),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('revision', models.CharField(default='A', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На проверке'), ('approved', 'Утверждён'), ('rejected', 'Отклонён'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('oem_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='marketplace.part')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
