# Generated by Django 5.1.6 on 2026-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_alter_order_status_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customs_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customs_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='mid_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mid_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_scheme',
            field=models.CharField(choices=[('simple', 'Стандартная (10% + 90%)'), ('staged', 'Поэтапная (10% + 50% + 40%)')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_reserve', 'Ожидает резерва'), ('reserve_paid', 'Резерв оплачен'), ('mid_paid', 'Подтверждение оплачено'), ('customs_paid', 'Таможня оплачена'), ('paid', 'Оплачен'), ('refund_pending', 'Возврат в обработке'), ('refunded', 'Возвращён')], default='awaiting_reserve', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('status_changed', 'Status Changed'), ('sla_status_changed', 'SLA Status Changed'), ('invoice_opened', 'Invoice Opened'), ('reserve_paid', 'Reserve Paid'), ('mid_payment_paid', 'Mid Payment Paid'), ('customs_payment_paid', 'Customs Payment Paid'), ('final_payment_paid', 'Final Payment Paid'), ('quality_confirmed', 'Quality Confirmed'), ('document_uploaded', 'Document Uploaded'), ('claim_opened', 'Claim Opened'), ('claim_status_changed', 'Claim Status Changed')], max_length=40),
        ),
    ]
