# Generated by Django 5.1.6 on 2026-03-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_order_customs_paid_at_order_customs_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Закупочная цена', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_scheme',
            field=models.CharField(choices=[('simple', '10% + 90%'), ('staged', '10% + 50% + 40%')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Поставщик'), ('operator', 'Оператор')], default='buyer', max_length=20),
        ),
    ]
