# Generated by Django 5.1.6 on 2026-04-02 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_order_customs_paid_at_order_customs_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Комментарий администратора (причина блокировки и т.д.)'),
        ),
        migrations.AddField(
            model_name='part',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Заметка администратора о поставщике'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_scheme',
            field=models.CharField(choices=[('simple', '10% + 90%'), ('staged', '10% + 50% + 40%')], default='simple', max_length=20),
        ),
    ]
