# Generated by Django 5.1.6 on 2026-04-06 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_part_admin_note_part_moderated_at_part_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['seller', '-data_updated_at', '-id'], name='part_seller_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['seller', 'availability_status'], name='part_seller_avail_idx'),
        ),
    ]
