# Generated by Django 5.1.6 on 2026-04-06 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_part_seller_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='order_buyer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'sla_status'], name='order_status_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='order_buyer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'event_type'], name='event_order_type_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['seller', 'is_active'], name='part_seller_active_idx'),
        ),
    ]
