# Generated by Django 5.1.6 on 2026-04-28 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_order_event_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'Не подавалась'), ('pending', 'На проверке'), ('verified', 'Верифицирована'), ('rejected', 'Отклонена')], db_index=True, default='none', max_length=20)),
                ('legal_name', models.CharField(blank=True, max_length=300)),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('doc_charter', models.FileField(blank=True, help_text='Устав', null=True, upload_to='kyb/charter/')),
                ('doc_egrul', models.FileField(blank=True, help_text='Выписка ЕГРЮЛ/ЕГРИП', null=True, upload_to='kyb/egrul/')),
                ('doc_passport', models.FileField(blank=True, help_text='Паспорт директора (1 разворот)', null=True, upload_to='kyb/passport/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyb', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', 'Информация'), ('order', 'Заказ'), ('rfq', 'RFQ'), ('payment', 'Оплата'), ('sla', 'SLA'), ('claim', 'Рекламация'), ('system', 'Система')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Optional click target', max_length=400)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='marketplace_user_id_4c2c73_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('logist', 'Логист'), ('finance', 'Финансист'), ('viewer', 'Только просмотр')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('invited', 'Приглашён'), ('disabled', 'Отключён')], default='invited', max_length=20)),
                ('invite_token', models.CharField(blank=True, max_length=100)),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(help_text='Company account owner', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Set when invitation accepted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('owner', 'invited_email')},
            },
        ),
    ]
