# Generated by Django 5.1.6 on 2026-05-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_twofactorauth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('seller_to_buyer', 'От продавца'), ('buyer_to_seller', 'От покупателя (counter)')], default='seller_to_buyer', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('countered', 'Контр-оффер от покупателя'), ('finalized', 'Финальная (без переторжки)'), ('accepted', 'Принята'), ('declined', 'Отклонена'), ('expired', 'Истекла')], db_index=True, default='submitted', max_length=20)),
                ('is_final', models.BooleanField(default=False, help_text='Продавец зафиксировал — переторжка невозможна')),
                ('delivery_days', models.PositiveIntegerField(default=14)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Комментарий к раунду')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='marketplace.quote')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='marketplace.rfq')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_offered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rfq', '-round_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(blank=True, help_text='Снимок названия на момент котировки', max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='marketplace.part')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.quote')),
                ('rfq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.rfqitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['rfq', 'seller', '-round_number'], name='quote_rfq_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', '-created_at'], name='quote_status_idx'),
        ),
    ]
