# Generated by Django 5.1.6 on 2026-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_quote_quoteitem_quote_quote_rfq_seller_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notif_email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_kinds',
            field=models.CharField(default='order,payment,rfq,sla,claim,system', help_text='Какие kinds доставлять через email/telegram (CSV)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat_id (получают через бот командой /start)', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_telegram_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
