# Generated by Django 5.1.6 on 2026-05-05 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_apitoken_magiclinktoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerVolumeYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('volume_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Без скидки'), (1, 'Уровень 1 (≥100M, 1%)'), (2, 'Уровень 2 (≥500M, 1.5%)'), (3, 'Уровень 3 (≥1B, 3%)')], default=0)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_yearly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['user', '-year'], name='bvy_user_year_idx'), models.Index(fields=['level'], name='bvy_level_idx')],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
