# Generated by Django 5.1.6 on 2026-05-05 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_buyervolumeyearly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclaim',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='kind',
            field=models.CharField(choices=[('defect', 'Брак'), ('wrong_part', 'Не та деталь'), ('missing', 'Не пришла'), ('damage', 'Повреждение при доставке'), ('late', 'Просрочка поставки'), ('other', 'Другое')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма возврата если resolution_kind=*_refund', max_digits=14),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='resolution_kind',
            field=models.CharField(choices=[('none', 'Нет'), ('repair', 'Замена/ремонт'), ('reproduce', 'Повторно произвести'), ('partial_refund', 'Частичный возврат'), ('full_refund', 'Полный возврат')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderclaim',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_review', 'На рассмотрении'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('corrective_actions', 'Корректирующие действия'), ('financial_settlement', 'Финансовое урегулирование'), ('closed', 'Закрыта')], db_index=True, default='open', max_length=30),
        ),
        migrations.AddIndex(
            model_name='orderclaim',
            index=models.Index(fields=['status', '-created_at'], name='claim_status_idx'),
        ),
    ]
