# Generated by Django 5.1.6 on 2026-05-05 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_orderclaim_closed_at_orderclaim_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('basis_fee', 'IT-Платформа FOB/CIF/DDP'), ('logistics_margin', 'Логистическая маржа'), ('success_fee', 'Success fee 5%'), ('rf_agent', 'РФ-агент 2%'), ('customs_fee', 'Customs $300'), ('volume_discount', 'Скидка по обороту (минус)')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pct', models.DecimalField(decimal_places=2, default=0, help_text='% использованный для расчёта (для basis_fee и logistics_margin)', max_digits=5)),
                ('basis', models.CharField(blank=True, choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('DDP', 'DDP'), ('EXW', 'EXW'), ('CIP', 'CIP')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_lines', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'kind'], name='rev_order_kind_idx'), models.Index(fields=['kind', '-created_at'], name='rev_kind_created_idx')],
            },
        ),
    ]
