# Generated by Django 5.1.6 on 2026-05-05 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0034_platformrevenueline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='access_level',
            field=models.CharField(choices=[('private', 'Закрытый — только владелец'), ('for_sale', 'Доступен для продажи (после предоплаты)'), ('rewardable', 'Доступен с вознаграждением автору')], default='private', help_text='ТЗ §3: закрытый/продажа/вознаграждение', max_length=20),
        ),
        migrations.AddField(
            model_name='drawing',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма вознаграждения автору при использовании в сделке (USD)', max_digits=10),
        ),
        migrations.CreateModel(
            name='DrawingAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('download', 'Скачивание'), ('denied', 'Отказано (нет прав)'), ('watermark_added', 'Применён watermark')], max_length=30)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='marketplace.drawing')),
                ('order', models.ForeignKey(blank=True, help_text='Заказ-контекст (для access_level=for_sale)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drawing', '-created_at'], name='dal_drw_created_idx'), models.Index(fields=['user', '-created_at'], name='dal_user_created_idx')],
            },
        ),
    ]
