# Generated by Django 5.1.6 on 2026-05-05 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_drawing_access_level_drawing_reward_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(blank=True, max_length=200)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('delivery_days', models.PositiveIntegerField(default=14)),
                ('file_url', models.URLField(blank=True, help_text='Скан/PDF предложения')),
                ('note', models.TextField(blank=True, help_text="Комментарий buyer'а")),
                ('status', models.CharField(choices=[('uploaded', 'Загружено'), ('under_review', 'Рассматривается'), ('matched', 'Скидка применена'), ('declined', 'Отклонено (наша цена ниже)')], default='uploaded', max_length=30)),
                ('seller_response_pct', models.DecimalField(decimal_places=2, default=0, help_text="Скидка от seller'а в ответ (% от quote.total_amount)", max_digits=5)),
                ('seller_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_offers', to='marketplace.quote')),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_offers', to='marketplace.rfq')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_offers_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rfq', '-created_at'], name='comp_rfq_created_idx'), models.Index(fields=['quote', '-created_at'], name='comp_quote_created_idx')],
            },
        ),
    ]
