# Generated by Django 5.1.6 on 2026-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_competitoroffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='mode',
            field=models.CharField(choices=[('auto', 'AUTO'), ('semi', 'SEMI'), ('manual', 'MANUAL'), ('manual_oem', 'MANUAL (legacy)')], default='semi', max_length=20),
        ),
    ]
