# Generated by Django 5.1.6 on 2026-05-05 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_alter_rfq_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('push', 'Push (платформа → ERP)'), ('pull', 'Pull (ERP → платформа)')], max_length=8)),
                ('kind', models.CharField(choices=[('parts', 'Каталог: цены/остатки'), ('orders', 'Заказы: новые на отгрузку'), ('order_ack', 'Подтверждение заказа от 1С'), ('status', 'Обновление статуса заказа')], max_length=20)),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='ok', max_length=8)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('external_ref', models.CharField(blank=True, db_index=True, help_text='Внешний идентификатор (для идемпотентности)', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Краткая выжимка содержимого для отладки')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='Чей ERP — обычно seller или operator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='erpsync_user_created_idx'), models.Index(fields=['kind', '-created_at'], name='erpsync_kind_created_idx')],
            },
        ),
    ]
