# Generated by Django 5.1.6 on 2026-05-05 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_erpsynclog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricelistMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_mapping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricelistImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(blank=True, upload_to='pricelists/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Превью (ждём подтверждения)'), ('imported', 'Импортирован'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='preview', max_length=20)),
                ('headers', models.JSONField(blank=True, default=list, help_text='Заголовки колонок, прочитанные из файла')),
                ('sample_rows', models.JSONField(blank=True, default=list, help_text='Первые 3 строки для AI и UI')),
                ('suggested_mapping', models.JSONField(blank=True, default=dict, help_text='Маппинг, предложенный AI (или предыдущий)')),
                ('final_mapping', models.JSONField(blank=True, default=dict, help_text="Маппинг, подтверждённый seller'ом")),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list, help_text='[{row, oem, reason}] первых ~50 ошибок')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', '-created_at'], name='pricelist_seller_created_idx')],
            },
        ),
    ]
