# Generated by Django 5.1.6 on 2026-05-05 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_pricelistmapping_pricelistimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='air_port',
            field=models.CharField(blank=True, help_text='Аэропорт отправления', max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='price_fob_air',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена FOB авиа', max_digits=12),
        ),
        migrations.AddField(
            model_name='part',
            name='price_fob_sea',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена FOB морским путём', max_digits=12),
        ),
        migrations.AddField(
            model_name='part',
            name='sea_port',
            field=models.CharField(blank=True, help_text='Морпорт отправления', max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='warehouse_address',
            field=models.CharField(blank=True, help_text='Адрес склада отправления', max_length=255),
        ),
    ]
