# Generated by Django 5.1.6 on 2026-05-05 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_part_air_port_part_price_fob_air_part_price_fob_sea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='hs_code',
            field=models.CharField(blank=True, db_index=True, help_text='Код ТН ВЭД / HS Code', max_length=20),
        ),
        migrations.CreateModel(
            name='LearnedColumnSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(db_index=True, help_text='Канонический ключ (part_number, description, …)', max_length=40)),
                ('raw_header', models.CharField(help_text='Оригинальный заголовок как из файла (для аудита)', max_length=200)),
                ('header_normalized', models.CharField(db_index=True, help_text='Нормализованный заголовок (lower + trim + без разделителей)', max_length=200, unique=True)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Ручной'), ('seed', 'Seed')], default='ai', max_length=20)),
                ('learned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('use_count', models.PositiveIntegerField(default=0, help_text='Сколько раз применялся (для аналитики)')),
            ],
            options={
                'ordering': ['-learned_at'],
                'indexes': [models.Index(fields=['canonical', '-learned_at'], name='lcs_canonical_idx')],
            },
        ),
    ]
