# Generated by Django 5.1.6 on 2026-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0041_part_hs_code_learnedcolumnsynonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistimport',
            name='created_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricelistimport',
            name='updated_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricelistimport',
            name='imported_rows',
            field=models.PositiveIntegerField(default=0, help_text='created + updated'),
        ),
    ]
