# Generated by Django 5.1.6 on 2026-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_pricelistimport_created_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistimport',
            name='ai_called',
            field=models.BooleanField(db_index=True, default=False, help_text='Был ли вызов AI для маппинга колонок (для лимита 3/день)'),
        ),
    ]
