# Generated by Django 5.1.6 on 2026-05-08 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_pricelistimport_ai_called'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Имя профиля (авто или ручное)', max_length=200)),
                ('headers_fingerprint', models.CharField(db_index=True, help_text='SHA256 от отсортированных нормализованных заголовков', max_length=64)),
                ('source_headers', models.JSONField(default=list, help_text='Оригинальные заголовки из файла')),
                ('column_mapping', models.JSONField(default=dict, help_text='{std_field: source_header_or_fix}')),
                ('transform_rules', models.JSONField(blank=True, default=dict, help_text='{std_field: {"formula": "price * 1.15", "type": "formula"}}')),
                ('constants', models.JSONField(blank=True, default=dict, help_text='{std_field: "fixed_value"} — поля с постоянными значениями')),
                ('header_row', models.PositiveIntegerField(default=1, help_text='Номер строки с заголовками (1-based)')),
                ('data_start_row', models.PositiveIntegerField(default=2, help_text='Номер строки, с которой начинаются данные (1-based)')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'headers_fingerprint'], name='marketplace_seller__cda6e4_idx'), models.Index(fields=['seller', '-updated_at'], name='marketplace_seller__f26715_idx')],
                'unique_together': {('seller', 'headers_fingerprint')},
            },
        ),
    ]
