# Generated by Django 5.1.6 on 2026-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_supplier_import_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistimport',
            name='ai_estimates',
            field=models.JSONField(blank=True, default=dict, help_text='AI-оценки per-part вес/габариты по описанию: {oem: {weight_kg, length_cm, ...}}'),
        ),
    ]
