# Generated by Django 5.1.6 on 2026-05-11 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0045_pricelistimport_ai_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_number', models.CharField(db_index=True, help_text='OEM-номер запчасти — основной ключ для lookup', max_length=100)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Бренд (Caterpillar, Komatsu, ...) — для уточнения lookup', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Название/описание из источника', max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hs_code', models.CharField(blank=True, db_index=True, help_text='Код ТН ВЭД из таможни', max_length=20)),
                ('country_of_origin', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(choices=[('customs', 'Таможенная декларация'), ('dealer', 'Дилер'), ('oem', 'OEM-каталог'), ('manual', 'Ручной ввод'), ('ai', 'AI-оценка')], db_index=True, default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text='Ссылка/ID в источнике (номер декларации, URL дилера, ...)', max_length=255)),
                ('confidence', models.FloatField(default=1.0, help_text='0.0-1.0. Для customs/dealer = 1.0, для AI = 0.7-0.9')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['oem_number', 'brand'], name='part_ref_oem_brand_idx'), models.Index(fields=['source', '-created_at'], name='part_ref_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('oem_number', 'brand', 'source'), name='uniq_part_ref_oem_brand_source')],
            },
        ),
    ]
