# Generated by Django 5.1.6 on 2026-05-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_partreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistimport',
            name='output_file',
            field=models.FileField(blank=True, help_text='Сгенерированный XLSX в формате маркетплейса (как у claude.ai)', null=True, upload_to='pricelist_outputs/%Y/%m/'),
        ),
    ]
