# Generated by Django 5.1.6 on 2026-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0047_pricelistimport_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Завод-производитель (для OEM — OEM-завод, для AFTERMARKET — завод аналога, для REMAN — завод восстановления)', max_length=200),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer_visible',
            field=models.BooleanField(default=True, help_text='Показывать завод клиенту. False — если бренд непубличный, хранится внутри'),
        ),
    ]
