# Generated by Django 5.1.6 on 2026-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0048_part_manufacturer_part_manufacturer_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistimport',
            name='output_preview_html',
            field=models.TextField(blank=True, help_text='Кэш HTML-превью первых 100 строк (для мгновенного preview)'),
        ),
        migrations.AddField(
            model_name='pricelistimport',
            name='output_total_rows',
            field=models.PositiveIntegerField(default=0, help_text='Сколько строк в output_file'),
        ),
    ]
