# Generated by Django 5.1.6 on 2026-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0049_pricelistimport_output_preview_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partreference',
            name='cross_numbers',
            field=models.CharField(blank=True, help_text='Перекрёстные номера (cross/reference numbers) из каталогов', max_length=500),
        ),
    ]
