# Generated by Django 5.1.6 on 2026-05-12 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_partreference_cross_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='warehouse_address',
            field=models.CharField(blank=True, help_text='Адрес склада отправления (денормализован из warehouse.address)', max_length=255),
        ),
        migrations.CreateModel(
            name='SellerWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное имя — продавец может менять', max_length=120)),
                ('country_code', models.CharField(blank=True, db_index=True, help_text='ISO-код страны отгрузки (TR/CN/RU/...)', max_length=2)),
                ('sea_port', models.CharField(blank=True, max_length=120)),
                ('air_port', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True, help_text='Полный адрес склада (страна, город, улица)')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Виртуальный склад поставщика — папка по логистическому базису', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='marketplace.sellerwarehouse'),
        ),
        migrations.AddIndex(
            model_name='sellerwarehouse',
            index=models.Index(fields=['seller', '-created_at'], name='warehouse_seller_idx'),
        ),
    ]
