# Generated by Django 5.1.6 on 2026-05-12 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0051_alter_part_warehouse_address_sellerwarehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['seller', 'oem_number'], name='part_seller_oem_idx'),
        ),
    ]
