# Generated by Django 5.1.6 on 2026-05-12 13:44

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0052_part_part_seller_oem_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_port', models.CharField(db_index=True, help_text='Порт отправления (CNNGB, TRMER, PKX и т.п.)', max_length=120)),
                ('dest_country', models.CharField(db_index=True, help_text='ISO-код страны назначения (RU, KZ, ...)', max_length=2)),
                ('mode', models.CharField(choices=[('sea', 'Морем'), ('air', 'Авиа')], db_index=True, max_length=4)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, help_text='USD за килограмм billable weight', max_digits=8)),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Минимальная стоимость отправления (USD)', max_digits=8)),
                ('transit_days', models.PositiveIntegerField(default=30, help_text='Среднее время в пути')),
                ('source', models.CharField(choices=[('internal', 'Внутренний тариф'), ('api_dhl', 'DHL API'), ('api_fedex', 'FedEx API'), ('api_other', 'Другой API')], default='internal', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['origin_port', 'dest_country', 'mode'],
                'indexes': [models.Index(fields=['origin_port', 'dest_country', 'mode'], name='tariff_route_idx')],
                'constraints': [models.UniqueConstraint(fields=('origin_port', 'dest_country', 'mode', 'source'), name='uniq_tariff_route')],
            },
        ),
    ]
