# Generated by Django 5.1.6 on 2026-05-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0053_logisticstariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incoterm',
            field=models.CharField(choices=[('FOB', 'FOB — продавец до порта отгрузки'), ('CIF', 'CIF — до порта назначения с фрахтом и страховкой'), ('DDP', 'DDP — до двери получателя, all-in')], default='FOB', help_text='Базис поставки Incoterms 2020', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(choices=[('sea', 'Морем'), ('air', 'Авиа')], default='sea', help_text='Способ доставки (выбирает покупатель)', max_length=4),
        ),
    ]
