# Generated by Django 5.1.6 on 2026-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0054_order_incoterm_order_shipping_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('zh-hans', '中文'), ('es', 'Español')], default='ru', help_text='Язык интерфейса. Меняется при регистрации или в настройках ЛК.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='incoterm',
            field=models.CharField(choices=[('FOB', 'FOB — продавец до порта отгрузки'), ('CIP', 'CIP — фрахт+страховка до места назначения'), ('DDP', 'DDP — до двери получателя, all-in')], default='FOB', help_text='Базис поставки Incoterms 2020', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(choices=[('sea', 'Морем'), ('air', 'Авиа'), ('auto', 'Авто')], default='sea', help_text='Способ доставки (выбирает покупатель)', max_length=4),
        ),
    ]
