# Generated by Django 5.1.6 on 2026-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0055_add_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('zh-hans', '中文'), ('es', 'Español'), ('ar', 'العربية')], default='ru', help_text='Язык интерфейса. Меняется при регистрации или в настройках ЛК.', max_length=10),
        ),
    ]
