# Generated by Django 5.1.6 on 2026-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0056_add_arabic_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyverification',
            name='api_results',
            field=models.JSONField(blank=True, default=dict, help_text='Снэпшоты API: {aggregator, opencorporates, vies, sanctions, maps, site, messenger}'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='auto_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='auto_decision',
            field=models.CharField(blank=True, default='', help_text='auto_reject / sandbox_candidate / manual_review', max_length=20),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='categories',
            field=models.CharField(blank=True, help_text='Бренды и типы запчастей (CSV или текст)', max_length=400),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='country',
            field=models.CharField(blank=True, help_text='ISO-2 страны регистрации: RU/CN/AE/DE/...', max_length=4),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='doc_bank',
            field=models.FileField(blank=True, help_text='Реквизиты банковского счёта (PDF/PNG)', null=True, upload_to='kyb/bank/'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='doc_dealership',
            field=models.FileField(blank=True, help_text='Сертификаты дилерства (если заявляет «официальный дилер»)', null=True, upload_to='kyb/dealership/'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='last_monitored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='operator_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='operator_note',
            field=models.TextField(blank=True, help_text='Свободный комментарий оператора при решении'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='risk_indicator',
            field=models.CharField(choices=[('green', 'Зелёный'), ('yellow', 'Жёлтый'), ('red', 'Красный'), ('unknown', 'Не определён')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='telegram',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT / Tax ID (если применимо)', max_length=40),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='warehouse_address',
            field=models.TextField(blank=True, help_text='Адрес склада, откуда реально отгружает'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='website',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
