# Generated by Django 5.1.6 on 2026-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0057_kyb_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_name',
            field=models.CharField(blank=True, help_text='ФИО контактного лица (кто работает с платформой)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='ISO-3166-1 alpha-2: RU, KZ, BY, AE, ...', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipment_fleet',
            field=models.TextField(blank=True, help_text='Парк техники: бренды и модели (любым текстом)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messenger_handle',
            field=models.CharField(blank=True, help_text='Username Telegram (@user) или номер WhatsApp (+7...)', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messenger_kind',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], help_text='Какой мессенджер: WhatsApp или Telegram', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_e164',
            field=models.CharField(blank=True, help_text='Телефон в международном формате (+7 ...)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Должность: закупщик / директор / владелец / иное', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, help_text='ИНН / Tax ID / Company Reg. No.', max_length=32),
        ),
    ]
