# Generated by Django 5.1.6 on 2026-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0058_buyer_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_email',
            field=models.EmailField(blank=True, help_text='Email перевозчика (для уточнений)', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_name',
            field=models.CharField(blank=True, help_text='DHL / UPS / СДЭК / Деловые Линии / внутренний курьер', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_phone',
            field=models.CharField(blank=True, help_text='Прямой телефон перевозчика (для buyer)', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Номер для трекинга на сайте перевозчика', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на статус (deep-link). Например dhl.com/track/...'),
        ),
    ]
