# Generated by Django 5.1.6 on 2026-05-19 04:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0059_order_carrier_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('registration', '📝 Регистрация'), ('kyb', '🛡 KYB / Верификация'), ('payment', '💰 Заказ и оплата'), ('delivery', '🚚 Доставка и сроки'), ('claims', '🧾 Рекламации'), ('contacts', '👥 Контакты сторон'), ('bonuses', '🎁 Бонусы'), ('platform', '⚙️ Платформа'), ('support', '🛟 Поддержка'), ('other', '❓ Другое')], db_index=True, default='other', max_length=20)),
                ('question', models.CharField(help_text='Короткий вопрос — отображается как заголовок', max_length=300)),
                ('answer', models.TextField(help_text='Полный ответ. Markdown НЕ поддерживается, plain-text.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Снимите чтобы скрыть entry без удаления.')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, help_text='Меньше число — выше в списке (для важных вопросов).')),
                ('views', models.PositiveIntegerField(default=0, help_text='Сколько раз показано (для аналитики популярности).')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
                'ordering': ['category', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='kb_cat_sort_idx')],
            },
        ),
    ]
