# Generated by Django 5.1.6 on 2026-05-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0060_knowledge_base_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclaim',
            name='escalated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда был отправлен алерт супервайзеру (защита от повторов)', null=True),
        ),
    ]
