# Generated by Django 5.1.6 on 2026-05-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0065_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consolidated', 'Консолидированная'), ('split', 'Split (раздельная)')], default='consolidated', max_length=20)),
                ('status', models.CharField(choices=[('formed', 'Сформирована'), ('ready_to_ship', 'Готова к отгрузке'), ('transit_abroad', 'Транзит (зарубеж)'), ('customs', 'Таможня'), ('transit_rf', 'Транзит (РФ)'), ('issuing', 'Выдача'), ('delivered', 'Доставлена')], default='formed', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('shipping_mode', models.CharField(blank=True, max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eta_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='shipments', to='marketplace.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='marketplace.order')),
            ],
        ),
    ]
