# Generated by Django 5.1.6 on 2026-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0066_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierratingevent',
            name='event_type',
            field=models.CharField(choices=[('rfq_response', 'RFQ Response'), ('rfq_response_late', 'RFQ Response Late'), ('data_mismatch', 'Data Mismatch'), ('delivery_delay', 'Delivery Delay'), ('delivery_on_time', 'Delivery On Time'), ('order_cancellation', 'Order Cancellation'), ('return', 'Return'), ('sandbox_selected', 'Sandbox Selected'), ('risky_selected', 'Risky Selected'), ('manual_oem_escalation', 'Manual OEM Escalation'), ('claim_confirmed', 'Claim Confirmed')], max_length=40),
        ),
    ]
