# Generated by Django 5.1.6 on 2026-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0067_alter_supplierratingevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('ved', 'Менеджер ВЭД'), ('logist', 'Логист'), ('finance', 'Финансист'), ('viewer', 'Только просмотр')], default='viewer', max_length=20),
        ),
    ]
