# Generated by Django 5.1.6 on 2026-06-04 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_wallettopuprequest'),
        ('marketplace', '0069_drawingfolder_drawing_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='assistant.project'),
        ),
    ]
