# Generated by Django 5.1.6 on 2026-06-04 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_wallettopuprequest'),
        ('marketplace', '0070_drawing_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='project_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='assistant.projectdocument'),
        ),
    ]
