# Generated by Django 5.1.6 on 2026-06-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0071_drawing_project_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='side',
            field=models.CharField(blank=True, choices=[('need', 'Нужно (покупатель)'), ('offer', 'Предлагают (продавец)')], db_index=True, max_length=10),
        ),
    ]
