# Generated by Django 5.1.6 on 2026-06-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0073_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_ref',
            field=models.ForeignKey(blank=True, help_text='Заказчик из CRM продавца, к которому относится этот заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.customer'),
        ),
    ]
