# Generated by Django 5.1.6 on 2026-06-05 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0074_order_customer_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Аккаунт заказчика после принятия инвайта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
