# Generated by Django 5.1.6 on 2026-06-05 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_kam(apps, schema_editor):
    """Проставить assigned_kam из владельца привязанного заказчика."""
    Order = apps.get_model('marketplace', 'Order')
    for o in Order.objects.filter(customer_ref__isnull=False, assigned_kam__isnull=True).select_related('customer_ref'):
        owner_id = getattr(o.customer_ref, 'owner_id', None)
        if owner_id:
            Order.objects.filter(pk=o.pk).update(assigned_kam_id=owner_id)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0075_customer_invite_token_customer_invited_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_kam',
            field=models.ForeignKey(blank=True, help_text='KAM — владелец аккаунта по этой сделке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kam_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_backfill_kam, _noop),
    ]
