# Generated by Django 5.1.6 on 2026-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0076_order_assigned_kam'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kam_handoff',
            field=models.CharField(choices=[('kam', 'У KAM'), ('operator', 'У оператора (исполнение)'), ('escalation', 'Эскалация к KAM')], db_index=True, default='kam', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='kam_handoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kam_handoff_note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
