# Generated by Django 5.1.6 on 2026-06-05 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0077_order_kam_handoff_order_kam_handoff_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(db_index=True, max_length=14, verbose_name='ТН ВЭД / HS')),
                ('commodity', models.CharField(blank=True, max_length=300, verbose_name='Товар')),
                ('oem_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Парт-номер')),
                ('direction', models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт')], default='import', max_length=8)),
                ('origin_country', models.CharField(blank=True, max_length=2, verbose_name='Страна происх.')),
                ('dest_country', models.CharField(default='RU', max_length=2, verbose_name='Страна назн.')),
                ('importer', models.CharField(blank=True, max_length=255, verbose_name='Импортёр')),
                ('importer_inn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Поставщик/отправитель')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('unit', models.CharField(blank=True, default='шт', max_length=20)),
                ('net_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('customs_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('period', models.DateField(blank=True, null=True, verbose_name='Период (месяц)')),
                ('source', models.CharField(blank=True, default='manual', max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period', '-created_at'],
                'indexes': [models.Index(fields=['hs_code', 'origin_country'], name='marketplace_hs_code_5db6e8_idx'), models.Index(fields=['oem_number'], name='marketplace_oem_num_ca1ea4_idx')],
            },
        ),
    ]
