# Generated by Django 5.1.6 on 2026-06-05 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0078_customsrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_role', models.CharField(blank=True, help_text='Роль пригласившего на момент приглашения', max_length=32)),
                ('kind', models.CharField(choices=[('flat_first_order', '$100 за первый заказ приглашённого'), ('buyer_discount', '−$100 на первый заказ (зачёт при пополнении)')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает условия'), ('credited', 'Зачислено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_given', to=settings.AUTH_USER_MODEL)),
                ('trigger_order', models.ForeignKey(blank=True, help_text='Заказ, активировавший начисление', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referred', 'status'], name='refrwd_referred_status_idx'), models.Index(fields=['referrer', '-created_at'], name='refrwd_referrer_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'flat_first_order')), fields=('referrer', 'referred', 'kind'), name='refrwd_uniq_flat_pair'), models.UniqueConstraint(condition=models.Q(('kind', 'buyer_discount')), fields=('referrer', 'kind'), name='refrwd_uniq_buyer_discount')],
            },
        ),
    ]
