# Generated by Django 5.1.6 on 2026-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0080_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='operator_role',
            field=models.CharField(blank=True, choices=[('', '—'), ('manager', 'KAM (менеджер по работе с клиентами)'), ('logist', 'Логист'), ('customs', 'Таможенный'), ('payment', 'Финансовый')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('operator', 'Operator')], default='buyer', max_length=20),
        ),
    ]
