# Generated by Django 5.1.6 on 2026-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0081_userprofile_operator_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_credits',
            field=models.IntegerField(default=25, help_text='Остаток бесплатных AI-запросов (для покупателей). Пополняется при оплате заказа.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_credits_refilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
