# Generated by Django 5.1.6 on 2026-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0082_userprofile_ai_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='condition',
            field=models.CharField(choices=[('oem', 'OEM'), ('analog', 'Аналог')], default='oem', help_text='Тип позиции: оригинал (OEM) или аналог', max_length=20),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, help_text='Срок поставки этой позиции (дни). Пусто → берём общий Quote.delivery_days', null=True),
        ),
    ]
