# Generated by Django 5.1.6 on 2026-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0084_alter_supplierratingevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
