# Generated by Django 5.1.6 on 2026-06-17 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0087_alter_supplierratingevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(blank=True, max_length=20)),
                ('signer_name', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(choices=[('ep', 'ПЭП (в платформе)'), ('upload', 'Загружен подписанный')], default='ep', max_length=10)),
                ('doc_sha256', models.CharField(blank=True, help_text='SHA-256 документа на момент подписи', max_length=64)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('signed_file', models.FileField(blank=True, help_text='Загруженный подписанный скан (method=upload)', upload_to='signed_documents/%Y/%m/%d')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='marketplace.orderdocument')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
    ]
