# Generated by Django 5.1.6 on 2026-06-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0091_part_trigram_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='source_import_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Номер загрузки (PricelistImport.id), которая последней записала эту позицию — для истории «Загрузка #N от завода X»', null=True),
        ),
        migrations.AddField(
            model_name='sellerwarehouse',
            name='kind',
            field=models.CharField(choices=[('pricelist', 'Прайс — большой каталог, склад по логистике'), ('kp', 'КП/расценка — папка по заводу-поставщику')], db_index=True, default='pricelist', help_text='pricelist=прайс (группа по логистике), kp=расценка (группа по заводу)', max_length=12),
        ),
        migrations.AddField(
            model_name='sellerwarehouse',
            name='supplier_country',
            field=models.CharField(blank=True, help_text='Юрисдикция поставщика (для типа налогового ID)', max_length=2),
        ),
        migrations.AddField(
            model_name='sellerwarehouse',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Название завода-поставщика (для КП)', max_length=200),
        ),
        migrations.AddField(
            model_name='sellerwarehouse',
            name='supplier_tax_id',
            field=models.CharField(blank=True, db_index=True, help_text='ИНН/USCC/VAT поставщика — ключ группировки КП', max_length=40),
        ),
    ]
