# Generated by Django 5.1.6 on 2026-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0092_part_source_import_id_sellerwarehouse_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwarehouse',
            name='is_full_catalog',
            field=models.BooleanField(db_index=True, default=False, help_text='КП-папка: полный каталог завода (отдельная на загрузку) vs накопительная папка КП (дедуп по заводу)'),
        ),
    ]
