# Generated by Django 5.1.6 on 2026-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0093_sellerwarehouse_is_full_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='oem_clean',
            field=models.CharField(blank=True, db_index=True, default='', help_text='OEM без спецсимволов, uppercase — для кроссреференса', max_length=100),
        ),
    ]
