# Generated by Django 5.1.6 on 2026-06-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0094_oem_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('hscode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('level', models.SmallIntegerField(choices=[(2, 'Глава'), (4, 'Группа'), (6, 'Субпозиция')])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='marketplace.hscode', to_field='hscode')),
            ],
            options={
                'ordering': ['hscode'],
            },
        ),
    ]
