# Generated by Django 5.1.6 on 2026-06-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0095_hscode_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='hs_verified',
            field=models.BooleanField(default=False, help_text='True = код подтверждён таможенным брокером'),
        ),
        migrations.AlterField(
            model_name='part',
            name='hs_code',
            field=models.CharField(blank=True, db_index=True, help_text='Код ТН ВЭД / HS Code — заполняется только брокером', max_length=20),
        ),
    ]
