# Generated by Django 5.2.16 on 2026-07-19 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_primary_roles(apps, schema_editor):
    UserProfile = apps.get_model("marketplace", "UserProfile")
    UserRole = apps.get_model("marketplace", "UserRole")
    for profile in UserProfile.objects.all().iterator():
        role = (profile.role or "buyer").strip().lower()
        if role not in {"buyer", "seller", "operator"}:
            role = "buyer"
        operator_role = (profile.operator_role or "").strip().lower() if role == "operator" else ""
        UserRole.objects.get_or_create(
            user_id=profile.user_id,
            role=role,
            operator_role=operator_role,
            defaults={"is_enabled": True},
        )


def unseed_primary_roles(apps, schema_editor):
    UserProfile = apps.get_model("marketplace", "UserProfile")
    UserRole = apps.get_model("marketplace", "UserRole")
    pairs = []
    for profile in UserProfile.objects.all().iterator():
        role = (profile.role or "buyer").strip().lower()
        if role not in {"buyer", "seller", "operator"}:
            role = "buyer"
        operator_role = (profile.operator_role or "").strip().lower() if role == "operator" else ""
        pairs.append((profile.user_id, role, operator_role))
    for user_id, role, operator_role in pairs:
        UserRole.objects.filter(user_id=user_id, role=role, operator_role=operator_role).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0096_hs_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('operator', 'Operator')], max_length=20)),
                ('operator_role', models.CharField(blank=True, choices=[('', '—'), ('manager', 'KAM (менеджер по работе с клиентами)'), ('logist', 'Логист'), ('customs', 'Таможенный'), ('payment', 'Финансовый')], default='', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'role', 'is_enabled'], name='marketplace_user_id_61ece2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'operator_role'), name='uniq_user_role_operator_role')],
            },
        ),
        migrations.RunPython(seed_primary_roles, unseed_primary_roles),
    ]
