# Generated by Django 5.2.16 on 2026-08-04 20:16

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0108_userprofile_public_party_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('status_changed', 'Status Changed'), ('sla_status_changed', 'SLA Status Changed'), ('invoice_opened', 'Invoice Opened'), ('reserve_paid', 'Reserve Paid'), ('mid_payment_paid', 'Mid Payment Paid'), ('customs_payment_paid', 'Customs Payment Paid'), ('final_payment_paid', 'Final Payment Paid'), ('payment_reported', 'Payment Reported'), ('payment_confirmed', 'Payment Confirmed'), ('payment_reversed', 'Payment Reversed'), ('quality_confirmed', 'Quality Confirmed'), ('document_uploaded', 'Document Uploaded'), ('claim_opened', 'Claim Opened'), ('claim_status_changed', 'Claim Status Changed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_reserve', 'Ожидает первого платежа'), ('reserve_paid', 'Первый платёж подтверждён'), ('mid_paid', 'Подтверждение оплачено'), ('customs_paid', 'Таможня оплачена'), ('paid', 'Оплачен'), ('refund_pending', 'Возврат в обработке'), ('refunded', 'Возвращён')], default='awaiting_reserve', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание оплаты'), ('reserve_paid', 'Первый платёж подтверждён'), ('confirmed', 'Формирование заказа'), ('in_production', 'В производстве'), ('ready_to_ship', 'Готов к отгрузке'), ('transit_abroad', 'Транзит (Зарубеж)'), ('customs', 'Таможня'), ('transit_rf', 'Транзит (РФ)'), ('issuing', 'Выдача'), ('shipped', 'Отгружен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='audience',
            field=models.CharField(choices=[('participants', 'All order participants'), ('buyer', 'Buyer and operators'), ('seller', 'Specified seller and operators'), ('operator', 'Operators only')], db_index=True, default='participants', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller allowed to access a seller-scoped document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_order_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='doc_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('buyer_contract', 'Buyer contract'), ('seller_contract', 'Seller procurement contract'), ('settlement_invoice', 'Settlement invoice'), ('payment_proof', 'Payment proof'), ('packing_list', 'Packing List'), ('certificate', 'Certificate'), ('quality_report', 'Quality Report'), ('customs', 'Customs'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='SettlementContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('buyer_sale', 'Договор поставки с покупателем'), ('seller_purchase', 'Закупочный договор с продавцом')], db_index=True, max_length=24)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Сформирован'), ('signed', 'Подписан'), ('active', 'Действует'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('platform_snapshot', models.JSONField(default=dict)),
                ('counterparty_snapshot', models.JSONField(default=dict)),
                ('terms_snapshot', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlement_contracts', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_contract', to='marketplace.orderdocument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_contracts', to='marketplace.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_id', 'kind', 'seller_id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('receivable', 'Покупатель должен платформе'), ('payable', 'Платформа должна продавцу')], db_index=True, max_length=16)),
                ('stage', models.CharField(choices=[('reserve', 'Первый платёж 10%'), ('final', 'Окончательный платёж 90%')], max_length=12)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('awaiting_confirmation', 'Покупатель сообщил об оплате'), ('partially_paid', 'Оплачен частично'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('payer_reported_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='marketplace.settlementcontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlement_invoices', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_invoice', to='marketplace.orderdocument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_invoices', to='marketplace.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Поступление от покупателя'), ('outgoing', 'Выплата продавцу')], max_length=12)),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждён'), ('reversed', 'Отменён обратной проводкой')], db_index=True, default='confirmed', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('bank_reference', models.CharField(help_text='Уникальный номер банковской операции или платёжного поручения.', max_length=160, unique=True)),
                ('paid_at', models.DateTimeField()),
                ('proof_file', models.FileField(blank=True, upload_to='settlement_payments/%Y/%m/%d')),
                ('note', models.CharField(blank=True, max_length=400)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_settlement_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='marketplace.settlementinvoice')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_settlement_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='settlementcontract',
            index=models.Index(fields=['status', '-created_at'], name='sett_contract_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'buyer_sale'), ('seller__isnull', True)), models.Q(('kind', 'seller_purchase'), ('seller__isnull', False)), _connector='OR'), name='sett_contract_seller_scope'),
        ),
        migrations.AddConstraint(
            model_name='settlementcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'buyer_sale')), fields=('order',), name='uniq_order_buyer_contract'),
        ),
        migrations.AddConstraint(
            model_name='settlementcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'seller_purchase')), fields=('order', 'seller'), name='uniq_order_seller_contract'),
        ),
        migrations.AddIndex(
            model_name='settlementinvoice',
            index=models.Index(fields=['direction', 'status', 'due_date'], name='sett_invoice_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementinvoice',
            index=models.Index(fields=['order', 'direction'], name='sett_invoice_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sett_invoice_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='settlementinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='sett_invoice_paid_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='settlementinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('amount'))), name='sett_invoice_paid_lte_amount'),
        ),
        migrations.AddConstraint(
            model_name='settlementinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'receivable'), ('seller__isnull', True)), models.Q(('direction', 'payable'), ('seller__isnull', False)), _connector='OR'), name='sett_invoice_seller_scope'),
        ),
        migrations.AddConstraint(
            model_name='settlementinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'receivable')), fields=('order', 'direction', 'stage'), name='uniq_order_receivable_stage'),
        ),
        migrations.AddConstraint(
            model_name='settlementinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'payable')), fields=('order', 'seller', 'direction', 'stage'), name='uniq_order_seller_payable_stage'),
        ),
        migrations.AddIndex(
            model_name='settlementpayment',
            index=models.Index(fields=['direction', 'status', '-paid_at'], name='sett_payment_report_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sett_payment_amount_gt_zero'),
        ),
    ]
