# Generated by Django 5.2.16 on 2026-08-08 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0109_orderdocument_audience_orderdocument_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms', 'Terms of use'), ('personal_data', 'Personal data processing')], db_index=True, max_length=32)),
                ('version', models.CharField(max_length=40)),
                ('source', models.CharField(choices=[('registration', 'Registration'), ('support', 'Support request'), ('admin', 'Administrative record')], default='registration', max_length=24)),
                ('document_url', models.CharField(max_length=255)),
                ('text_snapshot', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('granted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at', '-id'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-granted_at'], name='user_consent_lookup_idx')],
            },
        ),
    ]
