# Generated by Django 5.1.6 on 2026-03-17 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('csv', 'CSV File'), ('google_sheet', 'Google Sheet URL')], max_length=20)),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='files.storedfile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_error_reports', to='files.storedfile')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='error_report', to='imports.importjob')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_oem', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_brand', models.CharField(blank=True, default='', max_length=255)),
                ('parsed_name', models.CharField(blank=True, default='', max_length=255)),
                ('parsed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('parsed_quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('upserted', 'Upserted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_hint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='catalog.product')),
            ],
        ),
    ]
