# Generated by Django 5.1.6 on 2026-03-17 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='matched_supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='offers.supplieroffer'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['supplier', 'created_at'], name='imports_imp_supplie_b93b79_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['supplier', 'status'], name='imports_imp_supplie_1d6472_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'updated_at'], name='imports_imp_status_a2ef99_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['idempotency_key'], name='imports_imp_idempot_4d27f9_idx'),
        ),
        migrations.AddIndex(
            model_name='importerrorreport',
            index=models.Index(fields=['generated_at'], name='imports_imp_generat_244fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status'], name='imports_imp_job_id_b18fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'row_no'], name='imports_imp_job_id_7d7d82_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['normalized_oem'], name='imports_imp_normali_14b663_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['normalized_oem', 'normalized_brand'], name='imports_imp_normali_871393_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('job', 'row_no'), name='uq_import_row_job_row_no'),
        ),
    ]
