# Generated by Django 5.1.6 on 2026-03-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='error_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='valid_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
