# Generated by Django 5.1.6 on 2026-03-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('imports', '0003_importjob_error_rows_importjob_valid_rows_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='created_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='updated_offers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrow',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows_product', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows_supplier_offer', to='offers.supplieroffer'),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('upserted', 'Upserted'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
