# Generated by Django 5.1.6 on 2026-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcrossreference_catalogchangelog_payload_json_and_more'),
        ('imports', '0004_importjob_created_products_importjob_updated_offers_and_more'),
        ('offers', '0002_alter_supplieroffer_last_import_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='rows_created_offers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rows_created_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rows_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rows_matched_by_cross_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rows_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rows_updated_offers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rows_updated_prices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='summary_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='cross_number_normalized',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importrow',
            name='cross_number_raw',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importrow',
            name='match_status',
            field=models.CharField(choices=[('not_processed', 'Not processed'), ('matched', 'Matched'), ('matched_by_cross', 'Matched by Cross'), ('created_new_product', 'Created New Product'), ('ambiguous', 'Ambiguous'), ('failed', 'Failed')], default='not_processed', max_length=30),
        ),
        migrations.AddField(
            model_name='importrow',
            name='matched_by',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='part_number_normalized',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importrow',
            name='part_number_raw',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importrow',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='queued', max_length=30),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'validation_status'], name='imports_imp_job_id_76de3f_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'match_status'], name='imports_imp_job_id_e6519a_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['part_number_normalized'], name='imports_imp_part_nu_39ed80_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['cross_number_normalized'], name='imports_imp_cross_n_452376_idx'),
        ),
    ]
