# Generated by Django 5.1.6 on 2026-03-17 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_storedfile_mime_type_storedfile_original_filename'),
        ('imports', '0005_importjob_rows_created_offers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='column_mapping_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ImportPreviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('csv', 'CSV File'), ('google_sheet', 'Google Sheet URL')], max_length=20)),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('mapping_confirmed', 'Mapping Confirmed'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('detected_columns', models.JSONField(blank=True, default=dict)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_preview_sessions', to='files.storedfile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_preview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='importjob',
            name='preview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='imports.importpreviewsession'),
        ),
        migrations.AddIndex(
            model_name='importpreviewsession',
            index=models.Index(fields=['supplier', 'created_at'], name='imports_imp_supplie_cd8f73_idx'),
        ),
        migrations.AddIndex(
            model_name='importpreviewsession',
            index=models.Index(fields=['supplier', 'status'], name='imports_imp_supplie_f17a8f_idx'),
        ),
    ]
