# Generated by Django 5.1.6 on 2026-03-18 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_status', models.CharField(blank=True, default='', max_length=20)),
                ('user_role', models.CharField(blank=True, default='', max_length=40)),
                ('dashboard_state', models.CharField(choices=[('normal', 'Normal'), ('onboarding', 'Onboarding'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('new_rfqs_count', models.PositiveIntegerField(default=0)),
                ('orders_in_progress_count', models.PositiveIntegerField(default=0)),
                ('orders_sla_risk_count', models.PositiveIntegerField(default=0)),
                ('products_updated_24h', models.PositiveIntegerField(default=0)),
                ('import_errors_count', models.PositiveIntegerField(default=0)),
                ('imports_total', models.PositiveIntegerField(default=0)),
                ('failed_imports_30d', models.PositiveIntegerField(default=0)),
                ('last_catalog_update_at', models.DateTimeField(blank=True, null=True)),
                ('stale_products_count', models.PositiveIntegerField(default=0)),
                ('low_completeness_count', models.PositiveIntegerField(default=0)),
                ('permissions_summary_json', models.JSONField(blank=True, default=dict)),
                ('quick_actions_json', models.JSONField(blank=True, default=list)),
                ('widgets_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_dashboard_projections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dashboard_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'updated_at'], name='dashboard_d_supplie_4c60a2_idx'), models.Index(fields=['user', 'updated_at'], name='dashboard_d_user_id_175255_idx'), models.Index(fields=['dashboard_state'], name='dashboard_d_dashboa_38feb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'user'), name='uq_dashboard_projection_supplier_user')],
            },
        ),
    ]
