# Generated by Django 5.1.6 on 2026-03-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importjob_created_products_importjob_updated_offers_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieroffer',
            name='last_import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_offers_last_import', to='imports.importjob'),
        ),
    ]
