# Generated by Django 5.1.6 on 2026-03-17 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcrossreference_catalogchangelog_payload_json_and_more'),
        ('imports', '0005_importjob_rows_created_offers_and_more'),
        ('offers', '0002_alter_supplieroffer_last_import_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOfferPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoterm_basis', models.CharField(choices=[('EXW', 'EXW'), ('FOB', 'FOB')], max_length=10)),
                ('transport_mode', models.CharField(choices=[('NONE', 'None'), ('SEA', 'Sea'), ('AIR', 'Air')], default='NONE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='supplieroffer',
            name='uq_supplier_offer_supplier_product',
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='air_port',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('limited', 'Limited'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='condition',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('OEM', 'OEM'), ('AFTERMARKET', 'Aftermarket'), ('REMAN', 'Reman')], default='OEM', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='sea_port',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='warehouse_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='supplieroffer',
            index=models.Index(fields=['supplier', 'last_synced_at'], name='offers_supp_supplie_104656_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.UniqueConstraint(fields=('supplier', 'product', 'condition'), name='uq_supplier_offer_supplier_product_condition'),
        ),
        migrations.AddField(
            model_name='supplierofferprice',
            name='source_import_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_price_updates', to='imports.importjob'),
        ),
        migrations.AddField(
            model_name='supplierofferprice',
            name='supplier_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='offers.supplieroffer'),
        ),
        migrations.AddConstraint(
            model_name='supplierofferprice',
            constraint=models.UniqueConstraint(fields=('supplier_offer', 'incoterm_basis', 'transport_mode'), name='uq_supplier_offer_price_scenario'),
        ),
    ]
