# Generated by Django 5.1.6 on 2026-03-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0019_sellerimportrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parts', models.PositiveIntegerField(default=0)),
                ('active_parts', models.PositiveIntegerField(default=0)),
                ('recent_updates_24h', models.PositiveIntegerField(default=0)),
                ('import_runs_total', models.PositiveIntegerField(default=0)),
                ('import_runs_failed', models.PositiveIntegerField(default=0)),
                ('last_import_created', models.PositiveIntegerField(default=0)),
                ('last_import_updated', models.PositiveIntegerField(default=0)),
                ('last_import_errors', models.PositiveIntegerField(default=0)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('last_import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_projections', to='marketplace.sellerimportrun')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_projection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['refreshed_at'], name='projections_refresh_42526e_idx')],
            },
        ),
    ]
