"""ТЗ §12.2: генераторы документов по заказу (PDF).

  Commercial Invoice  — для оплаты + customs
  Packing List         — для отгрузки и приёмки
  Quality Report (QC)  — финальный контроль перед отгрузкой

Все три используют reportlab (чистый Python). Сохраняются в MEDIA_ROOT
с записью в OrderDocument (ссылка на файл + тип). Возвращают
ActionResult с download URL.

Actions:
  generate_invoice_pdf       — buyer / seller / operator
  generate_packing_list_pdf  — seller / operator
  generate_qc_report_pdf     — seller / operator
  list_order_documents       — все
"""
from __future__ import annotations

import io
import logging
import os
from decimal import Decimal

from django.conf import settings
from django.core.files.base import ContentFile
from django.utils import timezone

from .actions import ActionResult, register

logger = logging.getLogger(__name__)


# ── PDF helpers (reportlab) ──────────────────────────────────

def _pdf_canvas(title: str):
    """Создаёт reportlab Canvas + standard styles."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    c.setTitle(title)
    return c, buf


def _draw_header(c, title: str, doc_no: str | int):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    width, height = A4
    c.setFont("Helvetica-Bold", 18)
    c.drawString(20 * mm, height - 25 * mm, "CONSOLIDATOR PARTS")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(20 * mm, height - 35 * mm, title)
    c.setFont("Helvetica", 9)
    c.drawRightString(width - 20 * mm, height - 25 * mm,
                       f"№ {doc_no}")
    c.drawRightString(width - 20 * mm, height - 32 * mm,
                       timezone.now().strftime("%Y-%m-%d %H:%M UTC"))
    c.line(20 * mm, height - 40 * mm, width - 20 * mm, height - 40 * mm)
    return height - 50 * mm  # y-cursor


def _draw_kv_block(c, y, rows: list[tuple[str, str]]):
    from reportlab.lib.units import mm
    c.setFont("Helvetica", 10)
    for label, value in rows:
        c.drawString(20 * mm, y, f"{label}:")
        c.drawString(70 * mm, y, str(value))
        y -= 6 * mm
    return y - 4 * mm


def _draw_table(c, y, header: list[str], rows: list[list], widths: list[int]):
    """Простой табличный layout с заголовком на тёмном фоне."""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    x0 = 20 * mm
    row_h = 7 * mm

    # header
    c.setFillColor(colors.HexColor("#1f2937"))
    c.rect(x0, y - row_h + 1.5 * mm, sum(widths), row_h, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 9)
    x = x0
    for i, h in enumerate(header):
        c.drawString(x + 2 * mm, y - row_h + 4 * mm, h)
        x += widths[i]
    y -= row_h
    # rows
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 9)
    for row in rows:
        x = x0
        for i, cell in enumerate(row):
            txt = str(cell)
            if len(txt) > 38:
                txt = txt[:36] + "…"
            c.drawString(x + 2 * mm, y - row_h + 4 * mm, txt)
            x += widths[i]
        y -= row_h
    return y - 2 * mm


def _draw_footer(c):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    width, _ = A4
    c.setFont("Helvetica-Oblique", 7)
    c.setFillGray(0.4)
    c.drawCentredString(
        width / 2, 10 * mm,
        "Consolidator Parts · marketplace@consolidator.parts · "
        "Generated by Consolidator AI Assistant",
    )


# ── Save PDF buffer → OrderDocument ─────────────────────────

def _save_pdf(order, doc_type: str, title: str, buf: io.BytesIO,
              uploaded_by) -> "OrderDocument":
    from marketplace.models import OrderDocument
    filename = f"ORD-{order.id}-{doc_type}-{timezone.now():%Y%m%d-%H%M%S}.pdf"
    buf.seek(0)
    doc = OrderDocument.objects.create(
        order=order, doc_type=doc_type, title=title,
        uploaded_by=uploaded_by,
    )
    doc.file_obj.save(filename, ContentFile(buf.read()), save=True)
    return doc


def _doc_url(doc) -> str:
    """URL для download. Если file_obj.url доступен — берём его, иначе fallback."""
    try:
        return doc.file_obj.url
    except Exception:
        return doc.file_url or f"/media/order_documents/{doc.id}.pdf"


# ── Generators ──────────────────────────────────────────────

def _build_invoice_pdf(order) -> io.BytesIO:
    from reportlab.lib.units import mm
    c, buf = _pdf_canvas(f"Invoice ORD-{order.id}")
    y = _draw_header(c, "COMMERCIAL INVOICE", f"ORD-{order.id}")

    y = _draw_kv_block(c, y, [
        ("Buyer", order.customer_name or order.buyer.username if order.buyer else "—"),
        ("Email", order.customer_email or "—"),
        ("Delivery", order.delivery_address or "—"),
        ("Payment status", order.get_payment_status_display()),
        ("Order created", order.created_at.strftime("%Y-%m-%d") if order.created_at else "—"),
    ])

    rows = []
    for it in order.items.select_related("part").all():
        title = (it.part.title if it.part else "—") + (
            f" · {it.part.oem_number}" if it.part and it.part.oem_number else ""
        )
        rows.append([
            title,
            f"{it.quantity}",
            f"${it.unit_price:,.2f}",
            f"${(it.unit_price * it.quantity):,.2f}",
        ])
    y = _draw_table(
        c, y,
        header=["Position", "Qty", "Unit, USD", "Total, USD"],
        rows=rows,
        widths=[100 * mm, 20 * mm, 25 * mm, 25 * mm],
    )

    parts_total = sum(
        (it.unit_price * it.quantity) for it in order.items.all()
    ) or Decimal("0")
    logi = order.logistics_cost or Decimal("0")
    grand = parts_total + logi

    y -= 4 * mm
    y = _draw_kv_block(c, y, [
        ("Goods total",  f"${parts_total:,.2f}"),
        ("Logistics",    f"${logi:,.2f}"),
        ("INVOICE 100%", f"${grand:,.2f}"),
        ("Reserve 10%",  f"${order.reserve_amount or 0:,.2f}"),
        ("Outstanding",  f"${(grand - (order.reserve_amount or Decimal('0'))):,.2f}"),
    ])

    _draw_footer(c)
    c.showPage()
    c.save()
    return buf


def _build_packing_list_pdf(order) -> io.BytesIO:
    from reportlab.lib.units import mm
    c, buf = _pdf_canvas(f"Packing List ORD-{order.id}")
    y = _draw_header(c, "PACKING LIST", f"ORD-{order.id}")

    total_weight = Decimal("0")
    for it in order.items.select_related("part"):
        if it.part and it.part.gross_weight_kg:
            total_weight += Decimal(str(it.part.gross_weight_kg)) * it.quantity

    y = _draw_kv_block(c, y, [
        ("Buyer", order.customer_name or "—"),
        ("Delivery", order.delivery_address or "—"),
        ("Total positions", str(order.items.count())),
        ("Total gross weight", f"{total_weight:,.2f} kg"),
    ])

    rows = []
    for it in order.items.select_related("part"):
        p = it.part
        rows.append([
            (p.title if p else "—")[:38],
            (p.oem_number if p else "—"),
            f"{it.quantity}",
            f"{(p.gross_weight_kg if p else 0) or 0:.2f}",
            (p.country_of_origin if p else "—") or "—",
        ])
    y = _draw_table(
        c, y,
        header=["Title", "OEM", "Qty", "kg/pc", "Origin"],
        rows=rows,
        widths=[60 * mm, 35 * mm, 15 * mm, 20 * mm, 35 * mm],
    )

    y -= 6 * mm
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, "Inspector signature: ________________________")
    y -= 8 * mm
    c.drawString(20 * mm, y, "Date: ________________________")

    _draw_footer(c)
    c.showPage()
    c.save()
    return buf


def _build_qc_report_pdf(order) -> io.BytesIO:
    from reportlab.lib.units import mm
    c, buf = _pdf_canvas(f"QC Report ORD-{order.id}")
    y = _draw_header(c, "QUALITY CONTROL REPORT", f"ORD-{order.id}")

    y = _draw_kv_block(c, y, [
        ("Order", f"ORD-{order.id}"),
        ("Buyer", order.customer_name or "—"),
        ("Status", order.get_status_display() if order.status else "—"),
        ("Inspection date", timezone.now().strftime("%Y-%m-%d")),
    ])

    rows = []
    for it in order.items.select_related("part"):
        rows.append([
            (it.part.title if it.part else "—")[:42],
            f"{it.quantity}",
            "PASS",
            "—",
        ])
    y = _draw_table(
        c, y,
        header=["Position", "Qty", "Result", "Notes"],
        rows=rows,
        widths=[90 * mm, 20 * mm, 25 * mm, 35 * mm],
    )

    y -= 8 * mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(20 * mm, y, "Conclusion: All positions inspected and approved for shipment.")
    y -= 12 * mm
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, "QC Inspector: ________________________   Signature: ___________________")

    _draw_footer(c)
    c.showPage()
    c.save()
    return buf


# ── Public actions ──────────────────────────────────────────

def _get_order(params, user, role):
    """Returns (order, error_result|None). Order должен принадлежать user
    или к нему имеет доступ его роль (seller с item'ами, operator)."""
    from marketplace.models import Order, OrderItem
    try:
        order = Order.objects.get(id=int(params.get("order_id") or 0))
    except (Order.DoesNotExist, ValueError, TypeError):
        return None, ActionResult(text="Заказ не найден.")
    # Доступ: buyer = автор; seller = у заказа есть его part'ы; operator = всегда
    if role.startswith("operator") or user.is_staff:
        return order, None
    if order.buyer_id == user.id:
        return order, None
    # seller: проверяем что у него есть part'ы в этом заказе
    if OrderItem.objects.filter(order=order, part__seller=user).exists():
        return order, None
    return None, ActionResult(text="Нет доступа к этому заказу.")


@register("generate_invoice_pdf")
def generate_invoice_pdf(params, user, role):
    """ТЗ §12.2: коммерческий инвойс PDF на 100% суммы заказа."""
    order, err = _get_order(params, user, role)
    if err:
        return err
    try:
        buf = _build_invoice_pdf(order)
        doc = _save_pdf(order, "invoice", f"Invoice ORD-{order.id}", buf, user)
    except Exception as e:
        logger.exception("invoice PDF generation failed")
        return ActionResult(text=f"⚠️ Не удалось сгенерировать invoice: {e}")
    url = _doc_url(doc)
    return ActionResult(
        text=(
            f"✓ Commercial Invoice сгенерирован.\n"
            f"Заказ ORD-{order.id} · ${order.total_amount:,.2f}"
        ),
        cards=[{"type": "doc", "data": {
            "id": str(doc.id),
            "title": doc.title,
            "kind": "invoice",
            "url": url,
            "size_kb": (doc.file_obj.size // 1024) if doc.file_obj else None,
        }}],
        actions=[
            {"action": "open_url", "label": "📄 Открыть PDF", "params": {"_url": url}},
            {"action": "list_order_documents", "label": "Все документы заказа",
             "params": {"order_id": order.id}},
        ],
    )


@register("generate_packing_list_pdf")
def generate_packing_list_pdf(params, user, role):
    """ТЗ §12.2: packing list — состав отгрузки + вес/объём."""
    order, err = _get_order(params, user, role)
    if err:
        return err
    try:
        buf = _build_packing_list_pdf(order)
        doc = _save_pdf(order, "packing_list", f"Packing List ORD-{order.id}", buf, user)
    except Exception as e:
        logger.exception("packing list PDF generation failed")
        return ActionResult(text=f"⚠️ Не удалось сгенерировать packing list: {e}")
    url = _doc_url(doc)
    return ActionResult(
        text=f"✓ Packing List сгенерирован для ORD-{order.id}.",
        cards=[{"type": "doc", "data": {
            "id": str(doc.id), "title": doc.title, "kind": "packing_list",
            "url": url,
        }}],
        actions=[{"action": "open_url", "label": "📄 Открыть PDF", "params": {"_url": url}}],
    )


@register("generate_qc_report_pdf")
def generate_qc_report_pdf(params, user, role):
    """ТЗ §12.2: QC-отчёт перед отгрузкой."""
    order, err = _get_order(params, user, role)
    if err:
        return err
    try:
        buf = _build_qc_report_pdf(order)
        doc = _save_pdf(order, "quality_report", f"QC Report ORD-{order.id}", buf, user)
    except Exception as e:
        logger.exception("QC report PDF generation failed")
        return ActionResult(text=f"⚠️ Не удалось сгенерировать QC report: {e}")
    url = _doc_url(doc)
    return ActionResult(
        text=f"✓ QC Report сгенерирован для ORD-{order.id}.",
        cards=[{"type": "doc", "data": {
            "id": str(doc.id), "title": doc.title, "kind": "qc_report",
            "url": url,
        }}],
        actions=[{"action": "open_url", "label": "📄 Открыть PDF", "params": {"_url": url}}],
    )


@register("list_order_documents")
def list_order_documents(params, user, role):
    """Список всех документов заказа."""
    order, err = _get_order(params, user, role)
    if err:
        return err
    docs = order.documents.all().order_by("-created_at")
    if not docs:
        return ActionResult(
            text=f"По заказу ORD-{order.id} пока нет документов.",
            actions=[
                {"action": "generate_invoice_pdf", "label": "🧾 Создать invoice",
                 "params": {"order_id": order.id}},
                {"action": "generate_packing_list_pdf", "label": "📦 Packing list",
                 "params": {"order_id": order.id}},
                {"action": "generate_qc_report_pdf", "label": "✅ QC report",
                 "params": {"order_id": order.id}},
            ],
        )
    cards = [{"type": "doc", "data": {
        "id": str(d.id),
        "title": d.title,
        "kind": d.doc_type,
        "url": _doc_url(d),
        "created_at": d.created_at.strftime("%Y-%m-%d %H:%M") if d.created_at else "",
    }} for d in docs]
    return ActionResult(
        text=f"📄 Документы по заказу ORD-{order.id} ({len(cards)}):",
        cards=cards,
        actions=[
            {"action": "generate_invoice_pdf", "label": "+ Invoice",
             "params": {"order_id": order.id}},
            {"action": "generate_packing_list_pdf", "label": "+ Packing list",
             "params": {"order_id": order.id}},
            {"action": "generate_qc_report_pdf", "label": "+ QC report",
             "params": {"order_id": order.id}},
        ],
    )
