from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("demo-center/", views.demo_center, name="demo_center"),
    path("directory/brands/", views.brands_directory, name="brands_directory"),
    path("directory/categories/", views.categories_directory, name="categories_directory"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("catalog/", views.catalog, name="catalog"),
    path("rfq/", views.rfq_list, name="rfq_list"),
    path("rfq/new/", views.rfq_new, name="rfq_new"),
    path("rfq/<int:rfq_id>/", views.rfq_detail, name="rfq_detail"),
    path("rfq/<int:rfq_id>/proposal/", views.rfq_proposal, name="rfq_proposal"),
    path("rfq/<int:rfq_id>/proposal/pdf/", views.rfq_proposal_pdf, name="rfq_proposal_pdf"),
    path("rfq/<int:rfq_id>/proposal/logistics/", views.rfq_logistics_estimate, name="rfq_logistics_estimate"),
    path("rfq/<int:rfq_id>/checkout/", views.rfq_checkout, name="rfq_checkout"),
    path("operator/queue/", views.operator_queue, name="operator_queue"),
    path("operator/webhooks/", views.operator_webhooks, name="operator_webhooks"),
    path("operator/webhooks/retry-all/", views.operator_retry_failed_webhooks, name="operator_retry_failed_webhooks"),
    path("operator/webhooks/<int:log_id>/retry/", views.operator_retry_webhook, name="operator_retry_webhook"),
    path("operator/rfq-item/<int:rfq_item_id>/assign/", views.operator_assign_supplier, name="operator_assign_supplier"),
    path(
        "operator/rfq-item/<int:rfq_item_id>/manual-oem/",
        views.operator_escalate_manual_oem,
        name="operator_escalate_manual_oem",
    ),
    path("parts/<slug:slug>/", views.part_detail, name="part_detail"),
    path("compare/", views.compare_view, name="compare"),
    path("compare/add/<int:part_id>/", views.compare_add, name="compare_add"),
    path("compare/remove/<int:part_id>/", views.compare_remove, name="compare_remove"),
    path("compare/clear/", views.compare_clear, name="compare_clear"),
    path("cart/", views.cart_view, name="cart"),
    path("cart/add/<int:part_id>/", views.cart_add, name="cart_add"),
    path("cart/remove/<int:part_id>/", views.cart_remove, name="cart_remove"),
    path("checkout/", views.checkout, name="checkout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/buyer/", views.dashboard_buyer, name="dashboard_buyer"),
    path("dashboard/seller/", views.dashboard_seller, name="dashboard_seller"),
    path("reports/kpi/", views.kpi_reports, name="kpi_reports"),
    path("reports/kpi/export.csv", views.kpi_reports_export_csv, name="kpi_reports_export_csv"),
    path("reports/claims/export.csv", views.claims_export_csv, name="claims_export_csv"),
    path("orders/<int:order_id>/", views.order_detail, name="order_detail"),
    path("orders/<int:order_id>/invoice/", views.order_invoice, name="order_invoice"),
    path("orders/<int:order_id>/invoice/pdf/", views.order_invoice_pdf, name="order_invoice_pdf"),
    path("orders/<int:order_id>/reserve-paid/", views.order_mark_reserve_paid, name="order_mark_reserve_paid"),
    path("orders/<int:order_id>/final-paid/", views.order_mark_final_paid, name="order_mark_final_paid"),
    path("orders/<int:order_id>/mid-paid/", views.order_mark_mid_paid, name="order_mark_mid_paid"),
    path("orders/<int:order_id>/customs-paid/", views.order_mark_customs_paid, name="order_mark_customs_paid"),
    path("orders/<int:order_id>/confirm-quality/", views.order_confirm_quality, name="order_confirm_quality"),
    path("orders/<int:order_id>/documents/add/", views.order_add_document, name="order_add_document"),
    path("payments/callback/", views.payment_callback, name="payment_callback"),
    path("orders/<int:order_id>/claims/open/", views.order_open_claim, name="order_open_claim"),
    path("claims/<int:claim_id>/status/", views.order_update_claim_status, name="order_update_claim_status"),
    path("seller/orders/<int:order_id>/status/", views.seller_order_status_update, name="seller_order_status_update"),
    path("seller/", views.seller_dashboard, name="seller_dashboard"),
    path("seller/dashboard/", views.seller_dashboard, name="seller_dashboard_page"),
    path("seller/products/", views.seller_product_list, name="seller_product_list"),
    path("seller/requests/", views.seller_request_list, name="seller_request_list"),
    path("seller/requests/<int:rfq_id>/", views.seller_request_detail, name="seller_request_detail"),
    path("seller/orders/", views.seller_orders, name="seller_orders"),
    path("seller/sla/", views.seller_sla, name="seller_sla"),
    path("seller/drawings/", views.seller_drawings, name="seller_drawings"),
    path("seller/qr/", views.seller_qr_control, name="seller_qr_control"),
    path("seller/finance/", views.seller_finance, name="seller_finance"),
    path("seller/rating/", views.seller_rating, name="seller_rating"),
    path("seller/negotiations/", views.seller_negotiations, name="seller_negotiations"),
    path("seller/orders/<int:order_id>/", views.seller_order_detail, name="seller_order_detail"),
    path("seller/rfqs/", views.seller_rfq_inbox, name="seller_rfq_inbox"),
    path("seller/upload/", views.seller_bulk_upload, name="seller_bulk_upload"),
    path("seller/products/imports/<int:import_id>/", views.seller_import_result, name="seller_import_result"),
    path("seller/imports/preview/<int:preview_id>/", views.seller_import_preview, name="seller_import_preview"),
    path(
        "seller/imports/preview/<int:preview_id>/confirm/",
        views.seller_import_preview_confirm,
        name="seller_import_preview_confirm",
    ),
    path(
        "seller/imports/preview/<int:preview_id>/start/",
        views.seller_import_preview_start,
        name="seller_import_preview_start",
    ),
    path("seller/upload/template.csv", views.seller_csv_template, name="seller_csv_template"),
    path("seller/export/prices.csv", views.seller_price_export, name="seller_price_export"),
    path("seller/imports/<int:run_id>/errors.csv", views.seller_import_errors_csv, name="seller_import_errors_csv"),
    path("seller/parts/<int:part_id>/", views.seller_product_detail, name="seller_product_detail"),
    path("seller/parts/new/", views.seller_part_create, name="seller_part_create"),
    path("seller/parts/bulk-action/", views.seller_parts_bulk_action, name="seller_parts_bulk_action"),
    path("seller/parts/<int:part_id>/edit/", views.seller_part_edit, name="seller_part_edit"),
]
