# Generated by Django 5.1.6 on 2026-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('supplier_offer_created', 'Supplier Offer Created'), ('supplier_offer_updated', 'Supplier Offer Updated')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_raw', models.CharField(blank=True, default='', max_length=255)),
                ('oem_normalized', models.CharField(max_length=255)),
                ('brand_raw', models.CharField(blank=True, default='', max_length=255)),
                ('brand_normalized', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
