# Generated by Django 5.1.6 on 2026-03-17 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('imports', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogchangelog',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_changes', to='imports.importjob'),
        ),
        migrations.AddField(
            model_name='catalogchangelog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogchangelog',
            name='supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='offers.supplieroffer'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogchangelog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['oem_normalized'], name='catalog_pro_oem_nor_086f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['oem_normalized', 'brand_normalized'], name='catalog_pro_oem_nor_666e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_normalized'], name='catalog_pro_brand_n_24a9b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('oem_normalized', 'brand_normalized'), name='uq_product_oem_brand_normalized'),
        ),
        migrations.AddIndex(
            model_name='catalogchangelog',
            index=models.Index(fields=['import_job', 'created_at'], name='catalog_cat_import__2b6168_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogchangelog',
            index=models.Index(fields=['supplier', 'created_at'], name='catalog_cat_supplie_92a940_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogchangelog',
            index=models.Index(fields=['product', 'created_at'], name='catalog_cat_product_09fb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogchangelog',
            index=models.Index(fields=['change_type', 'created_at'], name='catalog_cat_change__7ac65f_idx'),
        ),
    ]
