# Generated by Django 5.1.6 on 2026-03-17 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('marketplace', '0019_sellerimportrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_number', models.CharField(max_length=255)),
                ('normalized_cross_number', models.CharField(max_length=255)),
                ('cross_type', models.CharField(choices=[('analog', 'Analog'), ('replacement', 'Replacement'), ('other', 'Other')], default='analog', max_length=20)),
                ('source', models.CharField(choices=[('import', 'Import'), ('manual', 'Manual')], default='import', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='catalogchangelog',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='marketplace.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='normalized_part_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['normalized_part_number'], name='catalog_pro_normali_af79a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'normalized_part_number'), name='uq_product_brand_part_number'),
        ),
        migrations.AddField(
            model_name='productcrossreference',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='productcrossreference',
            index=models.Index(fields=['normalized_cross_number'], name='catalog_pro_normali_441901_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcrossreference',
            constraint=models.UniqueConstraint(fields=('product', 'normalized_cross_number'), name='uq_product_cross_ref_product_number'),
        ),
    ]
