# Generated by Django 5.1.6 on 2026-03-17 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('import_csv', 'Import CSV'), ('import_google_sheet', 'Import Google Sheet'), ('import_error_report', 'Import Error Report'), ('other', 'Other')], default='other', max_length=40)),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=20)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'created_at'], name='files_store_supplie_472d6c_idx'), models.Index(fields=['source_type', 'created_at'], name='files_store_source__57f11e_idx'), models.Index(fields=['checksum_sha256'], name='files_store_checksu_da28e2_idx')],
            },
        ),
    ]
