# Generated by Django 5.1.6 on 2026-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
