# Generated by Django 5.1.6 on 2026-04-28 05:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Поставщик'), ('operator_logist', 'Логист'), ('operator_customs', 'Таможенный брокер'), ('operator_payment', 'Платёжный агент'), ('operator_manager', 'Менеджер по продажам'), ('admin', 'Администратор')], default='buyer', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('product', 'Товар'), ('brand', 'Бренд'), ('category', 'Категория'), ('order', 'Заказ'), ('rfq', 'RFQ'), ('shipment', 'Отгрузка'), ('document', 'Документ'), ('regulation', 'Регламент'), ('faq', 'FAQ')], max_length=20)),
                ('source_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, help_text='Vector as JSON list (SQLite fallback)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('zh', '中文')], default='ru', max_length=5)),
                ('access_roles', models.JSONField(default=list, help_text='Roles allowed to access: ["buyer","seller","operator_logist", ...]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='assistant_k_source__7f80bb_idx'), models.Index(fields=['language', 'is_active'], name='assistant_k_languag_779af0_idx')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Системное')], max_length=10)),
                ('content', models.TextField()),
                ('context_refs', models.JSONField(blank=True, default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='assistant_c_user_id_6ae267_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_m_convers_dbe832_idx'),
        ),
    ]
