# Generated by Django 5.1.6 on 2026-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_pgvector_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='Buttons: [{"label":"...","action":"...","params":{...}}]'),
        ),
        migrations.AddField(
            model_name='message',
            name='cards',
            field=models.JSONField(blank=True, default=list, help_text='Cards: [{"type":"product","data":{...}}, ...]'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Markdown text + ::: card blocks'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Системное'), ('action', 'Действие')], max_length=10),
        ),
    ]
