# Generated by Django 5.1.6 on 2026-04-29 07:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_message_actions_message_cards_alter_message_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code, e.g. NORQ2', max_length=50)),
                ('customer', models.CharField(blank=True, help_text='Customer name (Norilsk Nickel — Kola Division)', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Free-form tags: ["квартальная закупка","CAT 988H","793F"]')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('dot_color', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('gray', 'Gray')], default='green', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/')),
                ('doctype', models.CharField(choices=[('spec', 'Спецификация'), ('fleet', 'Парк техники'), ('drawing', 'Чертёж'), ('regulation', 'Регламент ТО'), ('conditions', 'Условия'), ('contract', 'Договор'), ('invoice', 'Счёт'), ('other', 'Другое')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обработка'), ('processed', 'Обработан'), ('error', 'Ошибка')], default='processed', max_length=20)),
                ('size_bytes', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='{rows, pages, units, ...}')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assistant.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'is_active', '-updated_at'], name='assistant_p_owner_i_d1b6d2_idx'),
        ),
    ]
