# Generated by Django 5.1.6 on 2026-05-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_wallet_wallettx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettx',
            name='kind',
            field=models.CharField(choices=[('topup', 'Пополнение'), ('debit', 'Списание'), ('refund', 'Возврат'), ('escrow_hold', 'Эскроу-холд'), ('escrow_release', 'Эскроу → продавцу'), ('escrow_refund', 'Эскроу → возврат')], max_length=20),
        ),
    ]
