# Generated by Django 5.1.6 on 2026-05-05 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_alter_wallettx_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(choices=[('general', 'Общее'), ('admin', 'Управление'), ('purchase', 'Покупка'), ('support', 'Поддержка')], db_index=True, default='general', help_text='Группа для reuse чата по типу задачи (admin/purchase/support/general)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'category', '-updated_at'], name='conv_user_cat_idx'),
        ),
    ]
