# Generated by Django 5.1.6 on 2026-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_conversation_category_conversation_conv_user_cat_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='category',
            field=models.CharField(choices=[('general', 'Общее'), ('admin', 'Управление'), ('purchase', 'Покупка'), ('support', 'Поддержка'), ('calc', 'Расчёт'), ('shipment', 'Сделка')], db_index=True, default='general', help_text='Группа для reuse чата по типу задачи (admin/purchase/support/general)', max_length=20),
        ),
    ]
