# Generated by Django 5.1.6 on 2026-05-19 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_alter_conversation_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('bank_wire', 'Банковский перевод'), ('card', 'Банковская карта'), ('usdt', 'USDT (TRC-20)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('awaiting_confirmation', 'Юзер сообщил об оплате — ждём подтверждения'), ('paid', 'Оплачено — депозит пополнен'), ('cancelled', 'Отменено пользователем'), ('failed', 'Платёж не прошёл'), ('expired', 'Истёк срок')], db_index=True, default='pending', max_length=30)),
                ('reference_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user_claim_at', models.DateTimeField(blank=True, help_text='Когда юзер кликнул «Я оплатил»', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='assistant_w_status_cae7bf_idx')],
            },
        ),
    ]
