# Generated by Django 5.1.6 on 2026-06-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_wallettopuprequest'),
        ('marketplace', '0073_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_ref',
            field=models.ForeignKey(blank=True, help_text='Заказчик из CRM продавца (если проект заведён под конкретного заказчика)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='marketplace.customer'),
        ),
    ]
