# Generated by Django 5.1.6 on 2026-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_project_customer_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='doctype',
            field=models.CharField(choices=[('spec', 'Спецификация'), ('fleet', 'Парк техники'), ('drawing', 'Чертёж'), ('regulation', 'Регламент ТО'), ('conditions', 'Условия'), ('contract', 'Договор'), ('invoice', 'Счёт'), ('pricelist', 'Прайс-лист'), ('certificate', 'Сертификат'), ('photo', 'Фото товара'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
