# Generated by Django 5.1.6 on 2026-06-29 14:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_alter_projectdocument_doctype'),
    ]

    operations = [
        # jsonb → vector нельзя кастовать через ALTER COLUMN ... USING,
        # поэтому дропаем старый столбец и создаём новый (данные теряются,
        # эмбеддинги будут перегенерированы).
        migrations.RunSQL(
            sql=[
                "ALTER TABLE assistant_knowledgechunk DROP COLUMN IF EXISTS embedding",
                "ALTER TABLE assistant_knowledgechunk ADD COLUMN embedding vector(1536)",
            ],
            reverse_sql=[
                "ALTER TABLE assistant_knowledgechunk DROP COLUMN IF EXISTS embedding",
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='knowledgechunk',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
                ),
            ],
        ),
    ]
